# Generated by Django 2.1 on 2019-07-31 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190731_1707'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('booking_number', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=200)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('canceled', models.BooleanField(default=False)),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Schedule_time')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_history_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.BookingHistory')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchedMovie',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wishMovie',
        ),
        migrations.AddField(
            model_name='watchedmovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movie_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
