# Generated by Django 2.1 on 2019-08-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_movie_star_user'),
        ('accounts', '0004_userstarrate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStarRate',
            new_name='StarRate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_star_rate',
        ),
    ]
