# Generated by Django 2.1 on 2019-08-07 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190806_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferTheater',
            field=models.TextField(blank=True, verbose_name='선호 영화관'),
        ),
    ]
