# Generated by Django 2.1 on 2019-08-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190807_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
    ]
