# Generated by Django 2.1 on 2019-07-09 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['cinema_name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age', models.IntegerField(choices=[(0, '전체 관람'), (12, '12세 관람가'), (15, '15세 관람가'), (19, '청소년 관람불가')], default=0)),
                ('type', models.IntegerField(choices=[(0, '2D'), (1, '3D'), (2, '4D'), (3, 'Digital')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_time', models.IntegerField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_id_detail', to='database.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_count', models.IntegerField()),
                ('available_seat', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('date_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_id_schedule', to='database.Schedule_date')),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_id_schedule', to='database.Movie')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField()),
                ('total_seat', models.IntegerField()),
                ('cinema_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinema_id', to='database.Cinema')),
            ],
            options={
                'ordering': ['screen_number'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=4)),
                ('available', models.BooleanField(default=True)),
                ('schedule_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_time_seat', to='database.Schedule_time')),
                ('screen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen_id_seat', to='database.Screen')),
            ],
        ),
        migrations.AddField(
            model_name='schedule_date',
            name='screen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_id_schedule', to='database.Screen'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_id', to='database.Region'),
        ),
    ]
