# Generated by Django 2.1 on 2019-07-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='available',
        ),
    ]
