# Generated by Django 2.1 on 2019-07-31 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190731_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='wish_movie',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
