# Generated by Django 2.1 on 2019-07-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_seat_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='screen_id',
        ),
    ]
