# Generated by Django 2.1 on 2019-07-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_seat_screen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='schedule_time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_time_seat', to='database.Schedule_time'),
        ),
    ]
