# Generated by Django 2.1 on 2019-08-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190731_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='wish_movie',
            new_name='wish_user',
        ),
    ]
