# Generated by Django 2.1 on 2019-08-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='region_id', to='database.Region'),
            preserve_default=False,
        ),
    ]
