# Generated by Django 2.1 on 2019-08-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_cinema_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
