# Generated by Django 2.1 on 2019-08-03 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190803_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='wish_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
