# Generated by Django 2.1 on 2019-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190803_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_star_rate',
            field=models.IntegerField(default=0),
        ),
    ]
