# Generated by Django 2.1 on 2019-08-06 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0009_movie_total_star_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star_user',
            field=models.ManyToManyField(related_name='user_rate', to=settings.AUTH_USER_MODEL),
        ),
    ]
