# Generated by Django 2.1 on 2019-08-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_movie_star_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='star_user',
        ),
    ]
