# Generated by Django 2.1 on 2019-08-07 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_movie_star_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='wish_user',
            field=models.ManyToManyField(blank=True, related_name='wish_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
