# Generated by Django 2.1 on 2019-08-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20190807_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.IntegerField(default=11000)),
                ('youth', models.IntegerField(default=7000)),
                ('favor', models.IntegerField(default=5000)),
            ],
        ),
    ]
