# Generated by Django 2.1 on 2019-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_priceinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceinfo',
            name='favor',
        ),
        migrations.RemoveField(
            model_name='priceinfo',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='priceinfo',
            name='youth',
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
